# Generated by Django 4.0.3 on 2022-03-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_alter_mahsulot_ichki'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='mamlakat',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
