# Generated by Django 4.0.3 on 2022-03-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_mahsulot_mamlakat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='mamlakat',
            field=models.CharField(blank=True, default='O`zbekiston', max_length=30),
        ),
    ]
